package de.moritzrupp.contractview.service.mapper;

import de.moritzrupp.contractview.domain.Contract;
import de.moritzrupp.contractview.service.dto.EventDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;
import org.mapstruct.factory.Mappers;

/**
 * Mapper for the entity Contract and its DTO called EventDTO.
 *
 * It is generated by using MapStruct
 */
@Mapper
public interface EventMapper {

    EventMapper INSTANCE = Mappers.getMapper(EventMapper.class);

    @Mappings({
        @Mapping(source = "name", target = "title"),
        @Mapping(source = "provider.name", target = "provider")
    })

    EventDTO contractToEventDTO(Contract contract);
}
