version: '2'
services:
    contractview-app:
        image: contractview
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://contractview-postgresql:5432/contractview
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    contractview-postgresql:
        extends:
            file: postgresql.yml
            service: contractview-postgresql
