version: '2'
services:
  contractview-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/contractview/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=contractview
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
